name: PR Build Test
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Test
      run: |
        git clone https://github.com/JeremyJaydan/jModifier .
        node ./.build/test.js
